/**
 * Vendors the three web fonts into public/fonts/ and generates
 * src/styles/fonts.css.
 *
 * Fonts are self-hosted deliberately: no runtime CDN request, no third-party
 * connection on first paint, no dependency on fonts.googleapis.com staying up.
 * Run once; re-run only when a family or weight changes.
 *
 *   node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";

const OUT_DIR = "public/fonts";
const CSS_OUT = "src/styles/fonts.css";

// Cyrillic + Ukrainian coverage is the hard requirement here — і ї є ґ and ₴.
const FAMILIES = [
  { name: "Geologica", weights: [700, 800] },
  { name: "Onest", weights: [400, 500, 600] },
  { name: "JetBrains Mono", weights: [500] },
];

const SUBSETS = new Set(["cyrillic", "cyrillic-ext", "latin", "latin-ext"]);
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const blocks = [];

  for (const family of FAMILIES) {
    const q = family.name.replace(/ /g, "+");
    const url =
      `https://fonts.googleapis.com/css2?family=${q}:wght@` +
      family.weights.join(";") + `&display=swap`;

    const css = await (await fetch(url, { headers: { "User-Agent": UA } })).text();

    // The Google CSS emits a /* subset */ comment before each @font-face, which
    // is the only way to know which unicode-range block we are looking at.
    const chunks = css.split("/*").slice(1);
    for (const chunk of chunks) {
      const subset = chunk.slice(0, chunk.indexOf("*/")).trim();
      if (!SUBSETS.has(subset)) continue;

      const weight = /font-weight:\s*(\d+)/.exec(chunk)?.[1];
      const range = /unicode-range:\s*([^;]+);/.exec(chunk)?.[1];
      const src = /src:\s*url\(([^)]+)\)/.exec(chunk)?.[1];
      if (!weight || !range || !src) continue;

      const bytes = Buffer.from(
        await (await fetch(src, { headers: { "User-Agent": UA } })).arrayBuffer(),
      );
      const slug = family.name.toLowerCase().replace(/ /g, "-");
      const hash = createHash("sha1").update(bytes).digest("hex").slice(0, 8);
      const file = `${slug}-${weight}-${subset}-${hash}.woff2`;
      await writeFile(`${OUT_DIR}/${file}`, bytes);

      blocks.push(
        `@font-face {\n` +
          `  font-family: "${family.name}";\n` +
          `  font-style: normal;\n` +
          `  font-weight: ${weight};\n` +
          `  font-display: swap;\n` +
          `  src: url("/fonts/${file}") format("woff2");\n` +
          `  unicode-range: ${range};\n}`,
      );
      process.stdout.write(`  ${file}\n`);
    }
  }

  await writeFile(
    CSS_OUT,
    `/* GENERATED by scripts/fetch-fonts.mjs — do not hand-edit.\n` +
      `   Self-hosted; no runtime CDN request. */\n\n` +
      blocks.join("\n\n") + "\n",
  );
  console.log(`\n${blocks.length} faces -> ${CSS_OUT}`);
}

main();
