/**
 * Vendors the three web fonts into public/fonts/ and generates
 * src/styles/fonts.css.
 *
 * Fonts are self-hosted deliberately: no runtime CDN request, no third-party
 * connection on first paint, no dependency on fonts.googleapis.com staying up.
 * Run once; re-run only when a family or weight changes.
 *
 *   node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";

const OUT_DIR = "public/fonts";
const CSS_OUT = "src/styles/fonts.css";

// Cyrillic + Ukrainian coverage is the hard requirement here — і ї є ґ and ₴.
const FAMILIES = [
  { name: "Geologica", weights: [700, 800] },
  { name: "Onest", weights: [400, 500, 600] },
  { name: "JetBrains Mono", weights: [500] },
];

const SUBSETS = new Set(["cyrillic", "cyrillic-ext", "latin", "latin-ext"]);
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  /** keyed by family|subset|content-hash, so identical bytes collapse */
  const faces = new Map();

  for (const family of FAMILIES) {
    const q = family.name.replace(/ /g, "+");
    const url =
      `https://fonts.googleapis.com/css2?family=${q}:wght@` +
      family.weights.join(";") + `&display=swap`;

    const css = await (await fetch(url, { headers: { "User-Agent": UA } })).text();

    // The Google CSS emits a /* subset */ comment before each @font-face, which
    // is the only way to know which unicode-range block we are looking at.
    const chunks = css.split("/*").slice(1);
    for (const chunk of chunks) {
      const subset = chunk.slice(0, chunk.indexOf("*/")).trim();
      if (!SUBSETS.has(subset)) continue;

      const weight = /font-weight:\s*(\d+)/.exec(chunk)?.[1];
      const range = /unicode-range:\s*([^;]+);/.exec(chunk)?.[1];
      const src = /src:\s*url\(([^)]+)\)/.exec(chunk)?.[1];
      if (!weight || !range || !src) continue;

      const bytes = Buffer.from(
        await (await fetch(src, { headers: { "User-Agent": UA } })).arrayBuffer(),
      );
      const hash = createHash("sha1").update(bytes).digest("hex").slice(0, 8);

      /* Onest and Geologica are variable fonts, so Google returns the SAME
         bytes for every weight. One file per weight meant three separate
         downloads of an identical file — 94 KB of pure waste, md5-verified.
         Group by content hash and emit one @font-face declaring a weight
         range instead. */
      const key = `${family.name}|${subset}|${hash}`;
      const seen = faces.get(key);
      if (seen) {
        seen.weights.push(Number(weight));
        continue;
      }
      const slug = family.name.toLowerCase().replace(/ /g, "-");
      const file = `${slug}-${subset}-${hash}.woff2`;
      await writeFile(`${OUT_DIR}/${file}`, bytes);
      faces.set(key, { family: family.name, file, range, weights: [Number(weight)] });
      process.stdout.write(`  ${file}\n`);
    }
  }

  const blocks = [...faces.values()].map((f) => {
    const lo = Math.min(...f.weights);
    const hi = Math.max(...f.weights);
    return (
      `@font-face {\n` +
      `  font-family: "${f.family}";\n` +
      `  font-style: normal;\n` +
      `  font-weight: ${lo === hi ? lo : `${lo} ${hi}`};\n` +
      `  font-display: swap;\n` +
      `  src: url("/fonts/${f.file}") format("woff2");\n` +
      `  unicode-range: ${f.range};\n}`
    );
  });

  await writeFile(
    CSS_OUT,
    `/* GENERATED by scripts/fetch-fonts.mjs — do not hand-edit.\n` +
      `   Self-hosted; no runtime CDN request.\n` +
      `   One @font-face per unique FILE, not per weight: these are variable\n` +
      `   fonts, so the weights share bytes and a weight range avoids\n` +
      `   downloading the same file several times. */\n\n` +
      blocks.join("\n\n") + "\n",
  );
  console.log(`\n${blocks.length} faces -> ${CSS_OUT}`);
}

main();
